account/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'login/$', views.UserLoginView.as_view(), name='user_login'),
    url(r'logout/$', views.UserLogoutView.as_view(), name='user_logout'),
]

shoppingcart/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers

from dashboard.views import CategoryViewSet, ProductViewSet
from dashboard import urls as dashboardUrl
from account import urls as accountUrl
from . import views

router = routers.DefaultRouter()
router.register(r'product', ProductViewSet)
router.register(r'category', CategoryViewSet)


urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'', include(dashboardUrl, namespace="dashboard")),
    url(r'^account/', include(accountUrl, namespace="account")),
    url(r'^$', views.home),
    url(r'checkout/$', views.checkout, name="checkout"),
    url(r'^cart/$', views.CartView.as_view(), name="cart"),
    url(r'^cart/remove_item/$', views.remove_item, name="remove_item"),
    url(r'^cart/discard_cart/$', views.discard_cart, name="discard_cart"),
    url(r'^cart/increased_item_quantity/$', views.increase_item_quantity, name="increased_item_quantity"),
    url(r'^cart/decreased_item_quantity/$', views.decrease_item_quantity, name="decreased_item_quantity"),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from __future__ import unicode_literals

from django.contrib.auth .models import AbstractUser, BaseUserManager
from django.db import models


class UserManager(BaseUserManager):

    def Create_user(self, email, date_of_birth, password=None):
        if not email:
            raise ValueError("users must have an email address")
        user = self.model(
            email=self.normalize_email(email),
            date_of_birth=date_of_birth
        )

        user.set_password(password)
        user.save(self._db)
        return user

    def Create_superuser(self, email, date_of_birth, password):
        """
        Create super user with given email ,date of birth and given password
        """
        user = self.create_user(email, password=password, date_of_birth=date_of_birth)
        user.is_admin = True
        user.save(self._db)
        return user


class Myuser(AbstractUser):
    """
    Custom user
    """
    role_choices = (
        ('admin', 'Administrator'),
        ('user', 'user')
    )
    role = models.CharField(max_length=7, choices=role_choices)
    mobile = models.CharField(max_length=10, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modifiedby = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.username

    def is_Admin(self):
        return True if self.role == 'admin' else False

    def is_user(self):
        return True if self.role == 'user' else False

dashboard/models.py
from __future__ import unicode_literals

from django.db import models


def image_upload_path(instance, filename):
    return filename


class Product(models.Model):
    active = models.CharField(max_length=200)
    cod = models.BooleanField()
    description = models.CharField(max_length=225)
    featured = models.CharField(max_length=200)
    image = models.ImageField(null=True, blank=True, upload_to=image_upload_path)
    name = models.CharField(max_length=225)
    price = models.FloatField()
    stock = models.IntegerField()
    title = models.CharField(max_length=225)

    def __unicode__(self):
        return self.name


class Category(models.Model):
    description = models.CharField(max_length=225)
    name = models.CharField(max_length=225)
    product = models.ManyToManyField(Product)
    parent_category = models.ForeignKey('self', null=True, blank=True)

    def __unicode__(self):
        return self.name

shoppingcart/models.py
import json
from time import time


from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Order(models.Model):
    status_choice = (
        ('initiated', 'initiated'),
        ('processing', 'processing'),
        ('dispatched', 'dispatched'),
    )
    payment_choice = (
        ('cod', 'cash on delivery'),
    )
    orderid = models.CharField(max_length=100, blank=True)
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    mobile = models.CharField(max_length=10, help_text='10 digit mobile number')
    address = models.CharField(max_length=300)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=100)
    pin = models.IntegerField(
        validators=[MaxValueValidator(999999), MinValueValidator(100000)],
        help_text='6 digit valid Postel code')
    status = models.CharField(max_length=20, choices=status_choice, default='initiated')
    payment_option = models.CharField(max_length=10, choices=payment_choice)
    items = models.TextField()
    total_price = models.FloatField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if (not self.pk) or (not self.orderid):
            self.orderid = str(time()).replace('.', '')
        super(Order, self).save(*args, **kwargs)

    @property
    def get_items(self):
        if self.items:
            items = json.loads(self.items)
            return items
        else:
            return []

templates/shop/checkout_form.html
<div ng-controller="checkoutCtrl">
    <h3>Checkout</h3>
    <form method="post" ng-submit="submit(field)">
        <div class="form-group">
            <label class="control-label" for="id_name">Name</label>
            <input class="form-control" id="id_name" maxlength="200" ng-model="checkout.name" placeholder="Name" required="required" title="" type="text" />
        </div>
        <div class="form-group">
            <label class="control-label" for="id_email">Email</label>
            <input class="form-control" id="id_email" maxlength="200" ng-model="checkout.email" placeholder="Email" required="required" title="" type="email" /></div>
        <div class="form-group">
            <label class="control-label" for="id_mobile">Mobile</label>
            <input class="form-control" id="id_mobile" maxlength="10" ng-model="checkout.mobile" placeholder="Mobile" required="required" title="10 digit mobile number" type="text" />
            <span class="help-block">10 digit mobile number</span>
        </div>
        <div class="form-group">
            <label class="control-label" for="id_address">Address</label>
            <input class="form-control" id="id_address" maxlength="300" ng-model="checkout.address" placeholder="Address" required="required" title="" type="text" />
        </div>
        <div class="form-group">
            <label class="control-label" for="id_city">City</label>
            <input class="form-control" id="id_city" maxlength="100" ng-model="checkout.city" placeholder="City" required="required" title="" type="text" />
        </div>
        <div class="form-group">
            <label class="control-label" for="id_state">State</label>
            <input class="form-control" id="id_state" maxlength="100" ng-model="checkout.state" placeholder="State" required="required" title="" type="text" />
        </div>
        <div class="form-group">
            <label class="control-label" for="id_pin">Pin</label>
            <input class="form-control" id="id_pin" ng-model="checkout.pin" placeholder="Pin" required="required" title="6 digit valid Postel code" type="number" />
            <span class="help-block">6 digit valid Postel code</span>
        </div>
        <div class="form-group">
            <label class="control-label" for="id_payment_option">Payment option</label>
            <select class="form-control" id="id_payment_option" ng-model="checkout.payment_option" required="required" title="">
                <option value="" selected="selected">---------</option>
                <option value="cod">Cash On Delievery</option>
            </select>
        </div>
        <button type="submit" class="btn btn-warning" data-target="#checkoutModal">Confirm Order</button>
        <a class="btn btn-primary" href="#/">cancel</a>
    </form>
</div>


<div id="checkoutModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Shopping Cart</h4>
                <lead> Thank you for placin order. Your order number is {/ order.orderid /}</lead>
            </div>
            <div class="modal-body">
                Order Items
                <ul>
                    <li ng-repeat="item in cart_items">
                        <span><img src='{/ item.image /}' height="50" width="50"></span>
                        <span>{/ item.name /}</span>
                        <span>X{/ item.quantity /}</span>
                        <span>&#x20b9;{/ item.price /} </span>
                    </li>
                </ul>
            </div>
            <div class="modal-footer">
                Total Price : {/ cart_total_price /}.
                Will be delievered to :<br/>
                {/ order.name /} <small>{/ order.mobile /}</small><br/>
                {/ order.address /}, {/ order.city /} - {/ order.pin /}
            </div>
        </div>

    </div>
</div>

templates/shop/home.html
{% load staticfiles %}
<html lang="en" ng-app="myApp">
<head>
<title>{% block title %}Shopping cart {% endblock title %}</title>
{% block meta %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link rel="stylesheet" href="/static/css/style.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0-rc.0/angular.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.25/angular-route.js"></script>
  <script src="/static/js/app.js"></script>
  <script src="/static/js/controller/master.js"></script>
  <script src="/static/js/controller/shop.js"></script>
  <script src="/static/js/controller/category.js"></script>
  <script src="/static/js/controller/product_details.js"></script>
  <script src="/static/js/controller/checkoutcontroller.js"></script>

{% endblock meta %}
</head>
<body ng-controller="MasterControllers">
<nav class="navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#/">Seaso9</a>
    </div>

    <ul class="nav navbar-nav navbar-right">
        <div class="cart">
        <span class="glyphicon glyphicon-shopping-cart right-icons" data-toggle="modal" data-target="#cartModal"></span>
        <span class="badge badge-notify">{/ cart_item_count /}</span>
    </div>
    </ul>
  </div>
</nav>
<nav class="navbar-default">
<ul class="dropdown" ng-repeat=
    "items in category">
  <div class="dropbtn"><a href="#/category/category_items/{/items.id/}/">{/items.name/}</a></div>
  <div class="dropdown-content">
    <a href="#">Link 1</a>
  </div>
</ul>
</nav>
<div class="container">

<div ng-view=""></div>
</div>
   <div class="category_items"></div>
<div id="cartModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Shopping Cart</h4>
            </div>
            <div class="modal-body">
                <span id="discard_cart_btn" class="glyphicon glyphicon-trash clickable" ng-click="discard_cart()"></span>
                <table class="table">
                <tr ng-repeat="item in cart_items">
                        <td><img src="{/item.image/}" height="50" width="50"></td>
                        <td>{/ item.name /}</td>
                        <td>x{/ item.quantity /}</td>
                        <td class="text-right">&#x20b9;{/item.price /} </td>
                        <td class="glyphicon glyphicon-remove clickable" ng-click="remove_cart_item(item.id)"></td>
                    </tr>
                </table>
            </div>
            <div class="modal-footer">
                        <div class="modal-footer">
                Total Price : {/ cart_total_price /}
                    <a button type="button" class="btn btn-primary" href="#/checkout/">Checkout</a>
            </div>
        </div>
    </div>
</div>
</div>



</body>
</html>