account/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'login/$', views.UserLoginView.as_view(), name='user_login'),
    url(r'logout/$', views.UserLogoutView.as_view(), name='user_logout'),
]

dashboard/urls.py
from django.conf.urls import url


from dashboard.views import DeleteProductView, ProductFormView, UpdateProductView, CategoryDetailsView, SubCategoryView


urlpatterns = [
    url(r'^products/$', ProductFormView.as_view(), name='home'),
    url(r'^(?P<pk>[0-9]+)/update/$', UpdateProductView.as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', DeleteProductView.as_view(), name='delete'),
    url(r'^api/category/category_details/(?P<category_id>[0-9]+)/$', CategoryDetailsView.as_view(), name='category_details'),
    url(r'^api/category/subcategory/$', SubCategoryView.as_view(), name='subcategory_details'),


]

shoppingcart/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers

from dashboard.views import CategoryViewSet, ProductViewSet
from dashboard import urls as dashboardUrl
from account import urls as accountUrl
from . import views

router = routers.DefaultRouter()
router.register(r'product', ProductViewSet)
router.register(r'category', CategoryViewSet)


urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'', include(dashboardUrl, namespace="dashboard")),
    url(r'^account/', include(accountUrl, namespace="account")),
    url(r'^$', views.home),
    url(r'checkout/$', views.checkout, name="checkout"),
    url(r'^cart/$', views.CartView.as_view(), name="cart"),
    url(r'^cart/remove_item/$', views.remove_item, name="remove_item"),
    url(r'^cart/discard_cart/$', views.discard_cart, name="discard_cart"),
    url(r'^cart/increased_item_quantity/$', views.increase_item_quantity, name="increased_item_quantity"),
    url(r'^cart/decreased_item_quantity/$', views.decrease_item_quantity, name="decreased_item_quantity"),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from __future__ import unicode_literals

from django.db import models


def image_upload_path(instance, filename):
    return filename


class Product(models.Model):
    active = models.CharField(max_length=200)
    cod = models.BooleanField()
    description = models.CharField(max_length=225)
    featured = models.CharField(max_length=200)
    image = models.ImageField(null=True, blank=True, upload_to=image_upload_path)
    name = models.CharField(max_length=225)
    price = models.FloatField()
    stock = models.IntegerField()
    title = models.CharField(max_length=225)

    def __unicode__(self):
        return self.name


class Category(models.Model):
    description = models.CharField(max_length=225)
    name = models.CharField(max_length=225)
    product = models.ManyToManyField(Product)
    parent_category = models.ForeignKey('self', null=True, blank=True)

    def __unicode__(self):
        return self.name

dashboard/forms.py
from django import forms
from .models import Product


class UpdateProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

dashboard/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.views.generic import View
from rest_framework import viewsets


from .forms import UpdateProductForm
from .models import Category, Product
from .serializers import ProductSerializer, CategorySerializer


class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer


class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.filter(parent_category__isnull=True)
    serializer_class = CategorySerializer


class ProductFormView(View):
    template_name = 'dashboard/home.html'

    def get(self, request, *args, **kwargs):
        product = Product.objects.all()
        return render(request, self.template_name, {'product': product})


class SubCategoryView(View):

    def get(self, request, *args, **kwargs):
        parent_category_list = Category.objects.filter(parent_category__isnull=True)
        for category_item in parent_category_list:
            category_id = category_item.name
            subcategory = Category.objects.filter(parent_category=category)
            subcategory_list = []
            for items in subcategory:
                subcategory_list.append({
                    'id': items.id,
                    'name': items.name,
                    'description': items.description,
                })
        parent_category_list.append({'subcategory_list': subcategory_list})
        return JsonResponse({"parent_category_list": parent_category_list})


class UpdateProductView(View):
    form_class = UpdateProductForm
    template_name = 'dashboard/product/updateProduct.html'

    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get("pk")
        instance = get_object_or_404(Product, pk=pk)
        form = self.form_class(request.POST or None, instance=instance)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        pk = self.kwargs.get("pk")
        instance = get_object_or_404(Product, pk=pk)
        form = self.form_class(request.POST or None, instance=instance)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('dashboard:home'))
        return render(request, self.template_name, {'form': form})


class DeleteProductView(View):

    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get("pk")
        product = get_object_or_404(Product, pk=pk)
        return render(request, 'dashboard/product/product_confirm_delete.html', {'product': product})

    def post(self, request, *args, **kwargs):
        pk = self.kwargs.get("pk")
        product = get_object_or_404(Product, pk=pk)
        product.delete()
        return HttpResponseRedirect(reverse('dashboard:home'))


class CategoryDetailsView(View):

    def get(self, request, *kwargs, **args):
        categoryid = self.kwargs['category_id']
        if categoryid:
            try:
                category = Category.objects.get(id=categoryid)
                product = category.product.all()
            except Category.DoesNotExist:
                return HttpResponse("category with this id DoesNotExist")
            prod_list = []
            for items in product:
                prod_list.append({
                    'id': items.id,
                    'name': items.name,
                    'description': items.description,
                    'stock': items.stock,
                    'price': items.price,
                    'image': items.image.url if items.image else '',
                })
            return JsonResponse({"product": prod_list})
        else:
            return HttpResponse("category Does Not Exist")

templates/dashboard/base.html
{% load staticfiles %}
<html lang="en" ng-app="myApp">
<head>
<title>{% block title %}Shopping cart {% endblock title %}</title>
{% block meta %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="/static/lib/bootstrap.min.css">
  <script src="/static/lib/jquery.min.js"></script>
  <script src="/static/lib/bootstrap.min.js"></script>
  <script src="/static/lib/angular.min.js"></script>
  <script src="/static/lib/angular-route.js"></script>
  <link rel="stylesheet" href="/static/css/style.css">
  <script src="/static/js/controller/app.js"></script>
  <script src="/static/js/controller/master.js"></script>

{% endblock meta %}
</head>
<body>
{% block nav %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Seaso9</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="#">Manage Products</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'account:user_login' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="{% url 'account:user_login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
{% endblock nav %}
{% block logo %}
{% endblock logo %}
<div class="container">
{% block breadcrumb %}
{% endblock breadcrumb %}
{% block content %}

 {% endblock content %}
</div>
</body>
</html>

templates/dashboard/home.html
{% extends 'dashboard/base.html' %}
<html>
{% block title %} Dashboard {% endblock title %}
{% block breadcrumb %}
 <ol class="breadcrumb">
    <li><a href="#">/Products</a></li>
    <li style="float:right"><a href="#">Go To Shop</a></li>
  </ol>
{% endblock breadcrumb %}
{% block content %}
 <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Price</th>
        <th>Stock</th>
        <th>Featured</th>
        <th>Active</th>
        <th>COD</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <tr>
      {% for item in product %}
        <td><img src='{{ item.image }}'/>{{item.title}}</td>
        <td>{{item.price}}</td>
        <td>{{item.stock}}</td>
        <td>{{item.featured}}</td>
        <td>{{item.active}}</td>
         <td><label><input type="checkbox" value="{{item.cod}}" checked></label></td>
         <td><a href="{% url 'dashboard:update' item.id%}"><span class="glyphicon glyphicon-pencil"></span></a></td>
        <td><a href="{% url 'dashboard:delete' item.id%}"><span class="glyphicon glyphicon-remove-circle"></span></a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}
</html>